name: Dependency Review
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 #v3
      - name: Dependency Review
        uses: actions/dependency-review-action@c090f4e553673e6e505ea70d6a95362ee12adb94 # v2
